### ISSUE TITLE
[1.18.2 Forge Bug]: Optifine crash

### ISSUE THREAD

**Issue by Gairlading** [DragonSurvivalTeam/DragonSurvival#144]
### ■ Your Discord ID

Gairlading#3776

### ■ Dragon Survival version

DragonSurvival_DragonEditorUpdate-1.18.2-0.11.0.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

Game crashed when generating new world.
(It seems that DS have something wrong with Optifine)

### ■ To Reproduce

1.Click the generate world button.
2.Game crashed. :(

### ■ Expected behavior

New world generated with no crash.

### ■ Crash Report

[crash-2022-04-11_20.23.35-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/8464263/crash-2022-04-11_20.23.35-client.txt)

**Comment by BlackAures1** [comment]
Better use these mods instead of Optifine. They don't crash and are much more effective.
https://www.curseforge.com/minecraft/mc-mods/sodium
or:
https://www.curseforge.com/minecraft/mc-mods/oculus
https://www.curseforge.com/minecraft/mc-mods/rubidium
https://www.curseforge.com/minecraft/mc-mods/radon 
https://www.curseforge.com/minecraft/mc-mods/radium-reforged
