### ISSUE TITLE
[1.18.2 Forge Bug]: Crash with breath on drawned

### ISSUE THREAD

**Issue by sethtnt** [DragonSurvivalTeam/DragonSurvival#248]
### ■ Your Discord ID

sethtnt#8074

### ■ Dragon Survival version

DragonSurvival-1.18.2-1.5.40

### ■ Single game or server?

Playing with friends over a local network (Hamachi, etc.)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

I'm using your mod pack to clarify the mods. The only new thing being a minimap mod. So basically I was a water dragon and I shot lightning (the ball version, not the breath) at a drowned and it threw a trident at me. They hit each other and started to bounce I think but it crashed before either of them could really go anywhere.

### ■ To Reproduce

I assume it will happen every time you hit a trident midair. Dunno if it happens with other dragon ball attacks.

### ■ Expected behavior

Probably to bounce or explode? Or maybe just to not really collide? Empower the trident? I don't really know.

### ■ Crash Report

[crash-2023-01-10_17.32.14-server.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/10387365/crash-2023-01-10_17.32.14-server.txt)

**Comment by BlackAures1** [comment]
I can't help with the bug itself. It happens sometimes randomly. But I can help you fix your map. Before you do all this, make a backup save (a copy of the world file)

1. Install **NBT explorer**  https://github.com/jaquadro/NBTExplorer/releases
2. Open your world (by default the program opens .minecraft, not Curseforge), find the parameter shown in the screenshot and fix it to other coordinates, so that your player is far away from the mob that causes the crash. There may be more than one player, find your own or fix it for everyone.
![image](https://user-images.githubusercontent.com/43911230/211690214-8b003322-5026-4da7-b7f7-d465e624203a.png)
3. Save the changes. 
4. If you have done everything correctly when you enter the game you should be in a different place and the problem mob despawns. For prevention, you can clear all aggressive mobs with `/incontrol kill hostile`

If you can't do it yourself, send me your save file.

**Comment by BlackAures1** [comment]
dublicate #252
