### ISSUE TITLE
[1.19.2 Forge Bug]: Pose stack not empty (crash)

### ISSUE THREAD

**Issue by Airisii** [DragonSurvivalTeam/DragonSurvival#407]
### ■ Your Discord ID or other contacts

airisii

### ■ Dragon Survival version and Modpack version (if have)

DragonSurvival-1.19.2-08.01.2024_fix

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Bug Description and Reproduce

Crash when hitting save in start dragon edit menu.

### ■ Expected behavior

Not to crash when saving the edit menu.

### ■ Crash Report File and Logs

[crash-2024-01-08_21.15.24-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/13868175/crash-2024-01-08_21.15.24-client.txt)
[latest.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/13868243/latest.log)

**Comment by Airisii** [comment]
Forgot to mention but this also occurs when trying to reenter the crashed world. Once the menu crashes, you can't get back into the world without it crashing.

**Comment by BlackAures1** [comment]
https://github.com/DragonSurvivalTeam/DragonSurvival/wiki/1.-Installation,-Configure,-Update#-installation
Try testing with geckolib + ds only. I can't replicate your bug

**Comment by Airisii** [comment]
It's multiple mods In my pack I believe. I've done so much testing and it's really hard to narrow it down because they all work fine when by themselves with the ds mod. I can send you the pack link that I am using it's a personal pack so it's on Google drive.

**Comment by Airisii** [comment]
I think it might be this: https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice/files/5000778 removing it from the pack seems to make it work. But It seems to work with just fine with ds by its self but in my pack its breaking.

**Comment by BlackAures1** [comment]
Alas, I can hardly help you with this, I don't have much time to test all possible incompatibilities among all existing mod combinations. The problem is in some of the mods that change the renderer. It could be anything. Send more logs and crashreport files, maybe there will be more information there

**Comment by Airisii** [comment]
[crash-2024-01-09_01.20.03-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/13869905/crash-2024-01-09_01.20.03-client.txt)
[2024-01-09-1.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/13869932/2024-01-09-1.log)
Here some new logs

**Comment by SiverDX** [comment]
another user also said sth. about mana and artifice having problems (but only when other mods are present?)
afaik it's because dragon survival cancels some rendering and the mod handles the pose stack across methods (so if one gets cancelled the pose stack doesn't get properly handled anymore)

might be best to add a notice for that mod

**Comment by Airisii** [comment]
Should I open an issue on mana and artifice's github?

**Comment by Tekatesha** [comment]
Howdy, I'm going to mention this dead issue as I'm continously having this problem. I have both MNA and Dragon Survival installed, though I really can't uninstall MNA to see if thats for sure causing the Pose Stack Error because the server is entirely based on it, and uninstalling it will break everything. Despite both MNA and Dragon Survival being installed, most players turn into Dragon form fine. For myself and two other people however, the second we turn into a dragon we get this pose stack crash. I am able to personally fix the problem occaisionally by messing with different versions of mods, and uninstalling some mods that have mixins, resulting in me able to be a dragon again but only for maybe a day before the problem comes back for some reason. None of these fixes that work for me work for the other two individuals however. 

Its also important to note that Me and one of the other two players were fine for weeks with both MNA and Dragon Survival working optimally, then it seemingly randomly started crashing us. The third player got on a few days ago, tried to go into dragon for the first time and immediately crashed. So its literally a different case for every single person, all resulting in the same crash:  @crash.
[crash-2024-03-26_03.33.07-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/14757712/crash-2024-03-26_03.33.07-client.txt)

 Reinstalling the modpack doesn't fix it, removing playerdata doesn't fix it, removing all items and skill points doesn't fix it, we've tried just about everything and cannot seem to restore dragon functionality to these specific individuals, even if the server effectively treats them as a new individual.

**Comment by SiverDX** [comment]
there is nothing this mod can do here
mana and artifice also had problems with other mods (like ice and fire)

a mod is responsible for properly handling the pose stack modifications they do
if they do so cross-method and don't account for mods utilizing features from events (such as cancelling them) then that's on them

**Comment by seelderr** [comment]
Pose stack issues are extremely hard to action on with more specific repro steps. There has also been a lot of pose stack call cleanup on our end since this issue was made.
