### ISSUE TITLE
[1.19.2 Forge Bug]: Forest Breath can be powered up unintentionally.

### ISSUE THREAD

**Issue by LeviticusTheFluff** [DragonSurvivalTeam/DragonSurvival#427]
### ■ Your Discord ID or other contacts

LeviticusTheFluff

### ■ Dragon Survival version and Modpack version (if have)

DragonSurvival 26.01.2024,  forge version 43.3.5

### ■ Single game or server?

Dedicated Server or Host Sites

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Bug Description and Reproduce

Forest Dragon breath is a deadly laser that can melt any mob in 3 seconds or less if a specific item is equipped by hitting the enemy 1000 times in 1 second. Full detailed report attached as a txt file. Bug discovered in the official Play as a Dragon server owned and operated by BlackAures
[Forest Dragon Laser Breath.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/14158753/Forest.Dragon.Laser.Breath.txt)

### ■ Expected behavior

Forest Dragon breath dealing minor-moderate lingering damage about once a second that doesnt behave differently based on what items you have equipped unless explicitly stated in that item's description.

### ■ Crash Report File and Logs

No crashes.

**Comment by SiverDX** [comment]
https://github.com/Shadows-of-Fire/Apotheosis/blob/8c41616c3b05e446abb3d718c37f46d963875033/src/main/java/shadows/apotheosis/core/attributeslib/impl/AttributeEvents.java#L145

this instance might be fixable by setting the damage here

https://github.com/DragonSurvivalTeam/DragonSurvival/blob/b8d8d912831301cc42c1f4b5df8cd1bd723f8ead/src/main/java/by/dragonsurvivalteam/dragonsurvival/magic/common/active/BreathAbility.java#L161

as magic (since the attribute damage only occurs for physical damage)
