### ISSUE TITLE
[1.19.2 Bug]: Cherry sapling?

### ISSUE THREAD

**Issue by Zhoff-blip** [DragonSurvivalTeam/DragonSurvival#539]
### ■ Dragon Survival version

Play as dragon gothic edition 18.05.2024.zip

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

I downloaded the modpack fully on curse forge. I changed out just a few mods as my laptop couldn't handle all 200+ mods (even though it handles the 1.18 dragons' survival?) it was popping up the exit 1 but after finer tuning I got it to load up the menu and even got it to start loading the game. Before it fully loads the game, it will crash the game and show me an error code unknown item vinery cherry sapling. I thought it was just due to me taking out the vinery mod but after putting it back in it still shows that issue. Any help is appreciated!

### ■ Crash Report File and Logs

[crash-2024-06-19_13.20.19-client.txt](https://github.com/user-attachments/files/15905624/crash-2024-06-19_13.20.19-client.txt)

**Comment by CaptianCarrot** [comment]
Did you make sure to allocate 8 gigs to the game as instructed on the forge site?

**Comment by CaptianCarrot** [comment]
Depending on your computer, the reason you might have been struggling with it before was because of that requirement. If you made the changes to the pack because it kept crashing, I’d recommend starting with that first and foremost with a fresh pack (feel free to move the current modified instance out of your Instances folder in Cursed forge) and see if it will run. 

If you made these changes _after_ having played and simply wanting to speed up your game, this might still help with your game actually running, but i personally won’t be able to help with the error you described

**Comment by SiverDX** [comment]
the goblin trader has been modified to contain items from the mod `vinery`
you removed said mod = it causes problems

**Comment by Zhoff-blip** [comment]
Took out the goblin trader and its finally working! I had updated the ram it was just that issue bugging it too hard. I am having a sound issue where breaking blocks and eating aren't producing any noise. I had this issue beforehand in the 1.18 dragons' survival but only when I had Xaero's mini map in the mod folder I've taken it off of the gothic edition and it's still not making any noise
