### ISSUE TITLE
When Generating a new world

### ISSUE THREAD

**Issue by AwsAlex** [DragonSurvivalTeam/DragonSurvival#55]
Generating a new world makes my game just Freeze and stop loading

https://pastebin.com/RYbGU42V

**Comment by AlexiyOrlov** [comment]
The error says "The process cannot access the file because it is being used by another process." for dragonsurvival-server.toml. It means that that file is opened by some application.

**Comment by BlackAures1** [comment]
This is a problem with Forge 36.2.0
Upgrade to version 36.2.8

**Comment by Claycorp** [comment]
There's no mention of anything related to changes to files being used by another processes in the Forge changelogs. 

Also if you are going to advocate people to use a specific forge version to fix forge bugs the mod should be set to require it.

**Comment by BlackAures1** [comment]
I said this after checking, not based on an assumption. I regularly have problems with the modpack on 36.2.0 when creating a new world. Please do not be misleading if you have not checked this information yourself.

**Comment by Claycorp** [comment]
I read the forge changelog myself.... [https://maven.minecraftforge.net/net/minecraftforge/forge/1.16.5-36.2.8/forge-1.16.5-36.2.8-changelog.txt](https://maven.minecraftforge.net/net/minecraftforge/forge/1.16.5-36.2.8/forge-1.16.5-36.2.8-changelog.txt)

I see no mention to anything related to world, file, config or otherwise between 36.2.0 and 36.2.8



Also it's still a known open issue on the Forge tracker here https://github.com/MinecraftForge/MinecraftForge/issues/7963

**Comment by BlackAures1** [comment]
Once again. I'm not talking about theory, I'm talking about practice. I very often created new worlds with the modpack and this problem was solved only by switching to a new version of Forge.  I have almost a 70% chance of having this problem on 36.2.0, but never on 36.2.8.
