### ISSUE TITLE
[1.20.1 Bug]: 

### ISSUE THREAD

**Issue by Draenaria** [DragonSurvivalTeam/DragonSurvival#571]
### ■ Your Discord ID or other contacts

Draenaria (otherwise Hope#0526)

### ■ Dragon Survival version

DragonSurvival-1.20.1-27.06.2024-all

### ■ Forge/Neoforge version

1.20.1-forge-47.3.0

### ■ Single game or server?

Self-made dedicated server

### ■ Describe the bug

I installed the mod correctly, and there was no issues for the first day to anyone (On this server, I am a player). When I logged in on the second day, parts of my skin were the wrong color, while any skin previews through the dragon altar or the skin tab through the dragon inventory appeared glitched and missing. I am uncertain of how to get this same result, nor do I know if anyone else could get this issue. Here's the link to the modpack: https://drive.google.com/file/d/1AHxGm81PN8SEFQioFgIKEZHdG-QbXSAF/view?usp=sharing
And here are the images to show how the skin/textures look currently, seems to only affect my textures, not the previews of other player's skins. (The initial design was warm colors, red/orange/yellow with black body and details, no blues whatsoever.)
![2024-07-05_15 58 17](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/174804498/aa6d5f91-fada-4e41-9e56-d41e7d54e219)
![2024-07-05_16 04 11](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/174804498/94ba9046-b09f-4acf-bf24-ecfe36aa0d90)

![2024-07-05_16 00 26](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/174804498/0fcfc69b-a53e-4bc4-9abb-0f1f5a5ecd65)
![2024-07-05_16 00 32](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/174804498/eaca20c8-4368-4362-948a-f04a8bdc574a)

**Comment by BlackAures1** [comment]
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/c621b08c-8d48-458e-9dfb-ea3b8ff78ef8)
 
  I think you just missed the changes between versions

**Comment by Psither** [comment]
The color selector was completely incorrect before, doing some bizarre math to your hue selection to get incorrect results.  I fixed the system (twice), the first time to make it so that when you select a hue, it will actually do the hue shift properly, which wrecked parts that had multiple colors before, and the second time to make it so you can select a part's color directly from the hue slider instead of playing around with hue shifting and trying to guess.

If your dragon's appearance used the old, busted hue system, you'll have to manually change the color back to what you wanted it to be after the update.  If you made a skin in the brief period between the two changes, it'll automatically update to the new system.

**Comment by Draenaria** [comment]
Removing those files did not seem to help, though notably I am able to edit/change the textures and look of my dragon through the altar, though the parts are all invisible unless they are glowing (then they are only transparent) while in the preview, though the model and textures and all of that seem to work just fine outside said preview.
