### ISSUE TITLE
[1.19.2 Bug]: 

### ISSUE THREAD

**Issue by LOPP47** [DragonSurvivalTeam/DragonSurvival#602]
### ■ Your Discord ID or other contacts

lopp#0335

### ■ Dragon Survival version

All versions

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

All the modpacks I added the mod to would freeze when loading the world. Even the official modpacks did this.

**Comment by KJEntytek303** [comment]
Might be caused by not enough RAM allocated to mc, and in case of Play as Dragon Gothic Edition if you allocate less than 8GB to minecraft (and you have at least 16 GB of RAM in your system) game will freeze when joining a world (regardless if server or singleplayer). For Play as Dragon Confort Edition it can run off 2 GB to mc and 8 GB in system, and for all other modpacks it should be fairly similar, depending on how demanding the modpack is.
