### ISSUE TITLE
Datapack support for dragon diets.

### ISSUE THREAD

**Issue by NotAPotter** [DragonSurvivalTeam/DragonSurvival#86]
What I hope is a helpful suggestion to make altering the food options for each dragon easier than altering a new world every time. I'll understand if there's an essential tactic I've just missed.

**Comment by BlackAures1** [comment]
There is a folder called "defaultconfigs" in any folder in mc. Just add your serverconfig there and you won't have to change the settings every time. 
But **we still recommend deleting all configs** before major updates. It's much better if you just manually copy the list into a new generated config.
We don't want to forcibly remove configs. Although the idea often comes up because of common complaints about people not following the recommendation to remove configs.
